# THERE WILL BW 3 FILES 1 JUPYTER NOTEBOOK 1 RECORDS.JSON 1 SALES.JSON
# 1. RECORDS.JSON WILL HAVE THE ITEMS RECORD. THE ADMIN WILL CHANGE THE ITEMS ID AND ITS ATTRIBUTES,ETC
# 2. SALES.JSON THIS FILL WILL HAVE THE DETAILS OF THE PURCHASES LIKE NUMBER OF ITEMS PURCHASED ITEMS REMAINING,ETC
# 3. JUPYTER NOTEBOOK WILL CONTAIN THE CODE TO MANIPULATE THE SALES.JSON AND RECORDS.JSON FILES AND ALSO THEY WILL HAVE THE PREVILAGE PERFORM CRUD OPERATION ON THE RECORD.JSON DATA
# **********THE MORE FUNCTIONALITY YOU HAVE THE MORE POINTS YOU GET**********

# STEPS TO COMPLETE THE PROJECT
# 1. CREATE RECORD.JSON FILE WHICH WILL HAVE ALL THE PRE LOADED 30 RECORDS.
# 2. OPEN THIS FILE IN JUPYTER NTBK(CODE) SO THAT THE USER CAN PERFORM CRUD OPERATIONS.
# 3. WRITE SOME FUNCTIONALITIES
# 4. ASK THE USER IF THEY WISH TO SAVE THE CHANGES TO RECORDS.JSON FILE.
# 5. IF YES THEN CHANGE THE RECORDS.JSON FILE AND ALSO SALES.JSON FILES TO COMMIT THE CHANGES. IF NOT THEN MAKE NO CHANGES IN THE RECORDS.JSON AND SALES.JSON FILES.


#THIS PROJECT IS MADE BY REFERING THE INVENTORY OF A COMPANY MAKING CLOTHES

#THIS IS LOGIN WHERE WE CHECK IF THE USER IS ADMIN COZ ADMIN IS HAVING COMPLETE PREVILAGE
import json

def authenticate():
    userName = input("Enter your user name : ")
    password = input("Enter your password : ")
    return "admin" if (userName == "admin" and password == "admin123") else userName

# userIs = authenticate() #admin IF USER IS PASSING ADMIN'S USERNAME AND PASSWORD ELSE USERNAME
# print(userIs)

with open("records.json") as f:
    data = json.load(f)
    print(data["raw_materials"])



